### ISSUE TITLE
Different configs for each driverstation

### ISSUE THREAD

**Issue by attempting-to-program** [FRC-Team-333-The-Megalodons/qr-scout-2024#14]
For each tablet, make a different dropdown list and merge teams and match into one dropdown menu

Alleviating the problem of scouting the wrong match as each tablet will have a different team that must be scouted

**Comment by brianjmaher** [comment]
this is gonna require a decent bit of work:
* we need a way to generate each config
* we need to improve the process of setting up each iPad
* we need to have a process for checking that everything is set up correctly

**Comment by attempting-to-program** [comment]
Tinkering with the sheet a bit, I have a way to generate a list that includes teams and their affiliated match number they'll be playing. 

![image](https://github.com/FRC-Team-333-The-Megalodons/qr-scout-2024/assets/92496218/b7a012e6-b123-43f4-8696-70e5f176dfb5)

![image](https://github.com/FRC-Team-333-The-Megalodons/qr-scout-2024/assets/92496218/8ad45e85-0bf6-4d13-8bae-1978277fb80e)

The output value for this when committed onto a spreadsheet is the team number, followed by the match, where both values are separated by a comma (e.g. "144,14"). Parsing the output is rather easy on the sheet, which will involve a simple 'split' formula for a given array column.

```
=arrayformula(split([array_column],","))
``` 

To verify that everything is set up correctly, we can change the title of the config to be whatever we want. In this instance, we can rename it to identify which DS is being setup for that particular tablet. 

Keep in mind that this whole setup must be done once schedules are out, which is usually around the end of practice day. The process of having that done overnight is worth thinking about.
